# v1.3 - это версия конфига, обновите, если на сервере используется старая версия

radius: 200                         # Дальность работы полёта игрока от гаста
slow-down-on-disable: true          # Включать ли плавное падение на 20 секунд после принудительного отключения статуса
slow-down-on-command-fly: false     # Включать ли плавное падение на 20 секунд после ручного отключения статуса
flights-into-normal: true           # Разрешён ли полёт в обычном мире?
flights-into-nether: true           # Разрешён ли полёт в аду?
flights-into-the-end: true          # Разрешён ли полёт в эндер мире?
flights-into-other: true            # Разрешён ли полёт в других мирах?

message:
  send-on-exit: true                              # Отправлять ли сообщение в конце езды на гасте?
                                                  # Сообщение в конце езды на гасте
  on-exit: "§aСтатус §eстроителя§a активирован. Он действует на территории радиусом 200 блоков."

  send-on-command-fly: true                       # Отправлять ли сообщение после команды `/fly`?
                                                  # Сообщение после команды `/fly`
  on-command-fly: "§cСтатус §eстроителя§c отключён."

  send-on-left-the-radius: true                   # Отправлять ли сообщение после принудительного отключения статуса?
                                                  # Сообщение после принудительного отключения статуса
  on-left-the-radius: "§cСтатус §eстроителя§c отключён. Вы улетели слишком далеко от гаста."