name: SitOnHappyGhastToFly
version: 'v1.5-paper1.21.10'
main: com.koolda.sitOnHappyGhastToFly.SitOnHappyGhastToFly
api-version: '1.21'

commands:
  fly:
    description: Включить/выключить полет
    usage: /fly
    aliases: [flight]